### ISSUE TITLE
click within the OSBuddy window

### ISSUE THREAD

**Issue by RazorTag** [RazorTag/runescape_bot#1]
ideally we want to do this without giving focus to the OSBuddy client so that it won't interrupt a user doing something else

**Comment by chiapet92** [comment]
any updates, Evan?

**Comment by RazorTag** [comment]
I have it doing boomerang clicks with absolute screen coordinates. A boomerang click is my term for moving the mouse, clicking, and returning the mouse to its original position. I am working clicking within a specific window that may not be on top.
